name: Run stardew/code/main.py

on:
  push:
    branches:
      - main # 推送到 main 分支時自動觸發

jobs:
  test-main:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # 限制 test-main 的執行時間
    steps:
      # 檢出儲存庫
      - name: Checkout repository
        uses: actions/checkout@v3

      # 設置 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # 安裝依賴項
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # check all files
      - name: List all files
        run: |
          ls -R

      # 執行 main.py
      - name: Run main.py with dummy audio
        run: |
          export SDL_AUDIODRIVER=dummy
          cd stardew/code
          python main.py
