name: Run NYCU VALLEY/code/zfortestmain.py

on:
  push:
    branches:
      - main

jobs:
  test-main:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出儲存庫原始碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # 3. 安裝依賴
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 列出所有檔案 (Debug 用，確認路徑是否正確)
      - name: List all files
        run: ls -R

      # 5. 安裝 xvfb 並執行 zfortestmain.py
      - name: Run zfortestmain.py in virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          
          # 切換到 NYCU VALLEY/code 目錄 (確保路徑正確，如果有空格須用引號)
          cd "NYCU VALLEY/code"
          
          # 設定 SDL_AUDIODRIVER / SDL_VIDEODRIVER
          export SDL_AUDIODRIVER=dummy
          export SDL_VIDEODRIVER=dummy
          
          # 使用 xvfb-run 執行 zfortestmain.py
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            python zfortestmain.py
